export default  {
  ON_BOARDING_SCREEN: 'ON_BOARDING_SCREEN',
  USER_TYPE_SCREEN: 'USER_TYPE_SCREEN',
  SIGN_IN_MEMBER_SCREEN: 'SIGN_IN_MEMBER_SCREEN',
  SIGN_IN_ADVISOR_SCREEN: 'SIGN_IN_ADVISOR_SCREEN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  //Member Screen
  HOME_MEMBER_SCREEN: 'HOME_MEMBER_SCREEN',
  MEMBER_PROFILE_SCREEN: 'MEMBER_PROFILE_SCREEN',
  LOAN_MEMBER_SCREEN: 'LOAN_MEMBER_SCREEN',
  TRANSACTION_MEMBER_SCREEN: 'TRANSACTION_MEMBER_SCREEN',
  PROFILE_MEMBER_SCREEN: 'PROFILE_MEMBER_SCREEN',
  MEMBER_BOTTOM_TAB: 'MEMBER_BOTTOM_TAB',
  MY_PROFILE_SCREEN: 'MY_PROFILE_SCREEN',
  NEW_INVESTMENT_SCREEN: 'NEW_INVESTMENT_SCREEN',
  BIOMETRIC_SCREEN: 'BIOMETRIC_SCREEN',
  CONTACTUS_SCREEN: 'CONTACTUS_SCREEN',
  POLICIES_SCREEN: 'POLICIES_SCREEN',
  CHANGEMPIN_SCREEN: 'CHANGEMPIN_SCREEN',

  //HOME SCREEN
  RENEWAL_SCREEN: 'RENEWAL_SCREEN',
  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
  APPLYLOAN_SCREEN: 'APPLYLOAN_SCREEN',
  MEMBERSUMMARY_SCREEN: 'MEMBERSUMMARY_SCREEN',
  UTILITYBILLPAYMENT_SCREEN: 'UTILITYBILLPAYMENT_SCREEN', 
  VIRTUALACCOUNT_SCREEN: 'VIRTUALACCOUNT_SCREEN',
  INTRATRANSFER_SCREEN: 'INTRATRANSFER_SCREEN',
  CALCULATOR_SCREEN: 'CALCULATOR_SCREEN',
  TRANSACTION_MEMBER_SCREEN: 'TRANSACTION_MEMBER_SCREEN',


  //CALCULATOR SCREEN
  POLICYCALCULATOR_SCREEN: 'POLICYCALCULATOR_SCREEN',
  LOANCALCULATOR_SCREEN: 'LOANCALCULATOR_SCREEN',
  NEFT_SCREEN: 'NEFT_SCREEN',
  IMPSTRANSFER_SCREEN: 'IMPSTRANSFER_SCREEN',

  
  //BENEFICIARY SCREEN
  ADDBENEFICIARY_SCREEN: 'ADDBENEFICIARY_SCREEN',

  //ACCOUNT STATEMENT SCREEN
  DAILYSTATEMENT_SCREEN: 'DAILYSTATEMENT_SCREEN',
  RECURRINGSTATEMENT_SCREEN: 'RECURRINGSTATEMENT_SCREEN',
  ANYAMOUNT_SCREEN: 'ANYAMOUNT_SCREEN',
  SAVINGSTATEMENT_SCREEN: 'SAVINGSTATEMENT_SCREEN',
  FDSTATEMENT_SCREEN: 'FDSTATEMENT_SCREEN',
  LOANSTATEMENT_SCREEN: 'LOANSTATEMENT_SCREEN',

  //ADVISOR SCREEN 
  HOME_ADVISOR_SCREEN: 'HOME_ADVISOR_SCREEN',
  ADVISOR_BOTTOM_TAB_SCREEN: 'ADVISOR_BOTTOM_TAB_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  LOAN_SCREEN: 'LOAN_SCREEN',
  KYC_SCREEN: 'KYC_SCREEN',

  // ADVISOR PROFILE SCREEN
  ADVISOR_PROFILE_SCREEN: 'ADVISOR_PROFILE_SCREEN',  
  ADVISOR_MPIN_SCREEN: 'ADVISOR_MPIN_SCREEN',  
  ADVISOR_LOCATION_SCREEN: 'ADVISOR_LOCATION_SCREEN',  
  ADVISOR_LOCATION_VIEW_SCREEN: 'ADVISOR_LOCATION_VIEW_SCREEN',  
  ADVISOR_BIOMETRIC_SCREEN: 'ADVISOR_BIOMETRIC_SCREEN',  
  ADVISOR_CONTACTUS_SCREEN: 'ADVISOR_CONTACTUS_SCREEN',  
  ADVISOR_BANKPOLICIES_SCREEN: 'ADVISOR_BANKPOLICIES_SCREEN',  

  //ADVISOR OTHER SCREEN
  ADVISOR_SAVING_ACCOUNT_SCREEN: 'ADVISOR_SAVING_ACCOUNT_SCREEN',
  ADVISOR_NEW_SAVING_ACCOUNT_SCREEN: 'ADVISOR_NEW_SAVING_ACCOUNT_SCREEN',
  ADVISOR_MINI_STATEMENT_SCREEN: 'ADVISOR_MINI_STATEMENT_SCREEN',
  ADVISOR_ADD_NEW_MEMBER_SCREEN: 'ADVISOR_ADD_NEW_MEMBER_SCREEN',
  ADVISOR_NEW_INVESTMENT_SCREEN: 'ADVISOR_NEW_INVESTMENT_SCREEN',
  ADVISOR_RENEWALS_SCREEN: 'ADVISOR_RENEWALS_SCREEN',
  ADVISOR_DAILY_RENEWALS_SCREEN: 'ADVISOR_DAILY_RENEWALS_SCREEN',
  ADVISOR_RECURRING_RENEWALS_SCREEN: 'ADVISOR_RECURRING_RENEWALS_SCREEN',
  ADVISOR_ALL_ACCOUNT_STATEMENT_SCREEN: 'ADVISOR_ALL_ACCOUNT_STATEMENT_SCREEN',
  ADVISOR_DAILY_STATEMENT_SCREEN: 'ADVISOR_DAILY_STATEMENT_SCREEN',
  ADVISOR_RECURRING_STATEMENT_SCREEN: 'ADVISOR_RECURRING_STATEMENT_SCREEN',
  ADVISOR_ALL_AMOUNT_STATEMENT_SCREEN: 'ADVISOR_ALL_AMOUNT_STATEMENT_SCREEN',
  ADVISOR_SAVING_STATEMENT_SCREEN: 'ADVISOR_SAVING_STATEMENT_SCREEN',
  ADVISOR_FD_STATEMENT_SCREEN: 'ADVISOR_FD_STATEMENT_SCREEN',
  ADVISOR_LOAN_STATEMENT_SCREEN: 'ADVISOR_LOAN_STATEMENT_SCREEN',
  ADVISOR_MEMBER_DETAILS_SCREEN: 'ADVISOR_MEMBER_DETAILS_SCREEN',
  ADVISOR_MY_INCENTIVE_SCREEN: 'ADVISOR_MY_INCENTIVE_SCREEN',
  ADVISOR_MY_TEAM_SCREEN: 'ADVISOR_MY_TEAM_SCREEN',
  ADVISOR_TEAM_DETAILS_SCREEN: ' ADVISOR_TEAM_DETAILS_SCREEN',
  ADVISOR_CALCULTOR_SCREEN: ' ADVISOR_CALCULTOR_SCREEN',
  ADVISOR_SAVING_TRANSACTION_SCREEN: ' ADVISOR_SAVING_TRANSACTION_SCREEN',
  ADVISOR_SAVING_HISTORY_SCREEN: ' ADVISOR_SAVING_HISTORY_SCREEN',

} 


