const ScreenConstants = {
  ON_BOARDING_SCREEN: 'ON_BOARDING_SCREEN',
  USER_TYPE_SCREEN: 'USER_TYPE_SCREEN',
  SIGN_IN_MEMBER_SCREEN: 'SIGN_IN_MEMBER_SCREEN',
  SIGN_IN_ADVISOR_SCREEN: 'SIGN_IN_ADVISOR_SCREEN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
} as const;

export default ScreenConstants;
